# Generated by Django 3.1.7 on 2021-04-13 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_profile', '0001_initial'),
        ('watch', '0006_auto_20210413_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='datetime')),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_orders', to='client_profile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField(default=1, verbose_name='count')),
                ('price', models.FloatField(default=0, verbose_name='price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order_details', to='watch.product')),
            ],
        ),
    ]
