# Generated by Django 3.1.7 on 2021-04-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_auto_20210408_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='product',
            name='with_discount',
            field=models.BooleanField(default=False, verbose_name='with discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no_image.jpg', help_text='Image resolution 380x361', upload_to='images/', verbose_name='image'),
        ),
    ]
