# Generated by Django 3.1.7 on 2021-04-13 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0005_remove_product_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'watch', 'verbose_name_plural': 'watch'},
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('product', 'price_type')},
        ),
    ]
