# Generated by Django 3.1.7 on 2021-05-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0006_auto_20210413_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetype',
            name='title',
            field=models.CharField(help_text='"regular" or "discounted"', max_length=255, verbose_name='price type'),
        ),
    ]
