# Generated by Django 3.1.7 on 2021-04-08 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='page name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='AboutItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('content', models.TextField(max_length=1000, verbose_name='content')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_about_items', to='pages.about')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='watch')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='page name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('contact_phone', models.CharField(max_length=16, verbose_name='contact phone')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('content', models.TextField(max_length=1000, verbose_name='content')),
                ('image', models.ImageField(default='no_image.jpg', upload_to='pages/', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_news', to='pages.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
