# Generated by Django 3.1.7 on 2021-04-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210408_1044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='NewsCategory',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Page_ABOUT', 'verbose_name_plural': 'Page_ABOUT'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Page_CONTACT', 'verbose_name_plural': 'Page_CONTACT'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
    ]
