# Generated by Django 3.1.7 on 2021-04-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210408_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name': 'news category', 'verbose_name_plural': 'news category'},
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='no_image.jpg', help_text='Image resolution 750x375', upload_to='news/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
